spring.application.name=oauthdemo
#spring.security.user.name=joy
#spring.security.user.password=joy@123
server.port=8000
spring.security.oauth2.client.registration.google.client-id=id
spring.security.oauth2.client.registration.google.client-secret=secret

spring.security.oauth2.client.registration.github.client-id=id
spring.security.oauth2.client.registration.github.client-secret=secret
